services:
  nestjs:
    build: .
    image: elena-chat-app
    env_file: .env
    environment:
      - TZ=${TZ}  # Zona horaria
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Monta la configuración de Nginx
      - ./public:/usr/share/nginx/html/public  # Monta los archivos estáticos desde "public"
    ports:
      - "80:80"
    depends_on:
      - nestjs
